package crucible_number_crunching;

import java.util.Arrays;
import java.util.List;

public enum WeaponCategory {
	HAND_CANNON,
	PULSE_RIFLE,
	SCOUT_RIFLE,
	AUTO_RIFLE,
	SIDEARM,
	SHOTGUN,
	FUSION,
	SNIPER,
	MACHINE_GUN,
	ROCKET_LAUNCHER;
	
	/*
	 * MACHINE_GUN - TEMPORARILY REMOVING BECAUSE I HAVE DOUBTS ON RELIABILITY OF EXXTROOPERS DATA
	 * SHOTGUN, FUSION - TEMPORARILY REMOVING UNTIL LESS EDGE-CASE-Y WEAPON CATEGORIES COMPLETED
	 * ROCKET_LAUNCHER - who cares?
	 */
	public final static List<WeaponCategory> EXXTROOPER_SUPPORTED_CATEGORIES = Arrays.asList(new WeaponCategory[]{HAND_CANNON, PULSE_RIFLE, SCOUT_RIFLE, AUTO_RIFLE, SIDEARM, SNIPER});
	
}
